// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.Models;

namespace PieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210421092036_ShoppingCartAdded")]
    partial class ShoppingCartAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.Property<int>("pieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pieCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("pieImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pieIsFavourite")
                        .HasColumnType("bit");

                    b.Property<string>("pieLongDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("piePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pieShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pieWeidth")
                        .HasColumnType("int");

                    b.HasKey("pieId");

                    b.HasIndex("pieCategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            pieId = 1,
                            pieCategoryId = 1,
                            pieImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg",
                            pieImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg",
                            pieIsFavourite = true,
                            pieLongDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            pieName = "Strawberry pie",
                            piePrice = 15.9m,
                            pieShortDesc = "Tastes Good",
                            pieWeidth = 200
                        },
                        new
                        {
                            pieId = 2,
                            pieCategoryId = 2,
                            pieImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            pieImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg",
                            pieIsFavourite = false,
                            pieLongDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            pieName = "Cheesecake pie",
                            piePrice = 16.3m,
                            pieShortDesc = "Tastes Good",
                            pieWeidth = 150
                        },
                        new
                        {
                            pieId = 3,
                            pieCategoryId = 3,
                            pieImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg",
                            pieImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg",
                            pieIsFavourite = true,
                            pieLongDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            pieName = "Rhurbarb pie",
                            piePrice = 14.6m,
                            pieShortDesc = "Tastes Good",
                            pieWeidth = 170
                        },
                        new
                        {
                            pieId = 4,
                            pieCategoryId = 1,
                            pieImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            pieImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            pieIsFavourite = true,
                            pieLongDesc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            pieName = "Pumpkin pie",
                            piePrice = 11.0m,
                            pieShortDesc = "Tastes Good",
                            pieWeidth = 120
                        });
                });

            modelBuilder.Entity("PieShop.Models.PieCategory", b =>
                {
                    b.Property<int>("pieCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pieCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pieCategoryId");

                    b.ToTable("PiesCategories");

                    b.HasData(
                        new
                        {
                            pieCategoryId = 1,
                            pieCategoryDescription = "Very delicious and good taste with freshest fruits.",
                            pieCategoryName = "Fruit pies"
                        },
                        new
                        {
                            pieCategoryId = 2,
                            pieCategoryDescription = "Cheesy all the way.",
                            pieCategoryName = "Cheese pies"
                        },
                        new
                        {
                            pieCategoryId = 3,
                            pieCategoryDescription = "Get in the mood for seasonal pie.",
                            pieCategoryName = "Seasonal pies"
                        });
                });

            modelBuilder.Entity("PieShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("shoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("amountOfPies")
                        .HasColumnType("int");

                    b.Property<int?>("pieId")
                        .HasColumnType("int");

                    b.Property<string>("shoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shoppingCartItemId");

                    b.HasIndex("pieId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.HasOne("PieShop.Models.PieCategory", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("pieCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PieShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("PieShop.Models.Pie", "pie")
                        .WithMany()
                        .HasForeignKey("pieId");
                });
#pragma warning restore 612, 618
        }
    }
}
