// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.Models;

namespace PieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210420095013_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.Property<int>("pieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pieCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("pieImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pieIsFavourite")
                        .HasColumnType("bit");

                    b.Property<string>("pieLongDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("piePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pieShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pieWeidth")
                        .HasColumnType("int");

                    b.HasKey("pieId");

                    b.HasIndex("pieCategoryId");

                    b.ToTable("Pies");
                });

            modelBuilder.Entity("PieShop.Models.PieCategory", b =>
                {
                    b.Property<int>("pieCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pieCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pieCategoryId");

                    b.ToTable("PiesCategories");
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.HasOne("PieShop.Models.PieCategory", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("pieCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
